import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Image from "next/image";
import ActiveSectionContextProvider from "../../context/active-section-context";
import { Toaster } from "react-hot-toast";

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Kaylie Fung - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={`${merriweather.className} relative h-[1000px] `}>
        <div className="relative w-screen lg:h-[3100px] sm:h-[3400px] min-[375px]:h-[3500px] ">
          <Image
            src="/background.png"
            alt="background"
            layout="fill"
            objectFit="cover"
            quality={100}
            priority={false}
          />
          <ActiveSectionContextProvider>
            <Header />
            {children}
            <Toaster position="top-center" />
          </ActiveSectionContextProvider>
        </div>
      </body>
    </html>
  );
}
